config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  get 'users/spotify'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :home, only: :index
  resources :artists, only: [:index, :show]
  resources :playlists, only: [] do
    get '/', to: 'playlists#show'
  end

  resources :tracks, only: [:index] do
    member do
      post :add_to_playlist
      post :remove_from_playlist
    end
  end
  resources :users, only: [:index, :show]

  # root 'playlists#show'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
	has_many :tracks, dependent: :destroy
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :user
  belongs_to :playlist

  def self.spotify_track_ids
    pluck(:spotify_track_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :tracks, dependent: :destroy

  def admin?
    admin == 'true'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    if params[:search].present?
      @artists = SpotifySearch.artists(params[:search])
    end
  end

  def show
    @artist = SpotifySearch.artist(params[:id])
    @top_tracks = @artist.top_tracks(:MX)
		@track_ids = Track.spotify_track_ids
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @tracks = User.joins(:tracks).group('users.id').select('users.*, MIN(tracks.created_at)').map(&:tracks).map(&:first)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_spotify_user

  def show
    # @playlist = RSpotify::Playlist.find(@spotify_user.id, SPOTIFY_PLAYLIST_ID)
  end

  private

  def set_spotify_user
    @spotify_user = RSpotify::User.new(JSON.parse($redis.get('spotify_credentials')))
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_playlist


  def index
    if params[:search].present?
      @tracks = RSpotify::Track.search(params[:search], limit: 3, market: 'MX')
    end

    @track_ids = Track.spotify_track_ids
  end

  # Stimulus endpoints
  def add_to_playlist
    # spotify_user = RSpotify::User.new(JSON.parse($redis.get('spotify_credentials')))
    # playlist_id = $redis.get('playlist_id')
    # playlist = SpotifyPlaylist.find(spotify_user.id, playlist_id)

    track = RSpotify::Track.find(params[:id])

    begin
      # playlist.add_tracks!([track])
      current_user.tracks.create(
        spotify_track_id: track.id,
        name: track.name,
        album_image_url: track.album.images.select{|i| i['height'] == 300 }.first['url'] || 'https://via.placeholder.com/300x300',
        artist: track.artists.map(&:name).join(' & '),
        playlist_id: @playlist.id
      )

      render json: { track_name: track.name }, status: :ok
    rescue => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end

  def remove_from_playlist
    spotify_user = RSpotify::User.new(JSON.parse($redis.get('spotify_credentials')))
    playlist = SpotifyPlaylist.find(spotify_user.id, SPOTIFY_PLAYLIST_ID)

    track = RSpotify::Track.find(params[:track_id])

    begin
      playlist.remove_tracks!([track])
      current_user.tracks.find_by(spotify_track_id: track.id).destroy

      render json: { track_name: track.name, user_id: current_user.id }, status: :ok
    rescue => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end

  private
  
  def set_playlist
    @playlist = Playlist.find_or_create_by(name: 'Party playlist')
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

    def sign_up_params
      params.require(:user).permit(:name, :password, :password_confirmation, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = current_user
		@tracks = @user.tracks.order(:created_at)
	end

  def spotify
    spotify_credentials = request.env['omniauth.auth']

    $redis.set('spotify_credentials', spotify_credentials.to_json)

    # # Access token available in request.env['omniauth.auth']C 
    # playlist = spotify_user.create_playlist!('party-playlist')
    # tracks = RSpotify::Track.search('Ella baila sola')
    # playlist.add_tracks!(tracks)

    # # Access private data
    # spotify_user.country #=> "US"
    # spotify_user.email   #=> "example@email.com"

    # # Create playlist in user's Spotify account
    # playlist = spotify_user.create_playlist!('my-awesome-playlist')

    # # Add tracks to a playlist in user's Spotify account
    # tracks = RSpotify::Track.search('Know')
    # playlist.add_tracks!(tracks)
    # playlist.tracks.first.name #=> "Somebody That I Used To Know"

    # # Access and modify user's music library
    # spotify_user.save_tracks!(tracks)
    # spotify_user.saved_tracks.size #=> 20
    # spotify_user.remove_tracks!(tracks)

    # albums = RSpotify::Album.search('launeddas')
    # spotify_user.save_albums!(albums)
    # spotify_user.saved_albums.size #=> 10
    # spotify_user.remove_albums!(albums)

    # # Use Spotify Follow features
    # spotify_user.follow(playlist)
    # spotify_user.follows?(artists)
    # spotify_user.unfollow(users)

    # # Get user's top played artists and tracks
    # spotify_user.top_artists #=> (Artist array)
    # spotify_user.top_tracks(time_range: 'short_term') #=> (Track array)

    # # Check doc for more
    redirect_to root_path, notice: 'Authenticated!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def format_datetime(datetime)
		datetime.in_time_zone('America/Mexico_City').strftime("%d/%m/%Y %H:%M")
	end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/index.html.erb
<h3 class="text-center">Buscar artista</h3>

<div class="col-md-10 offset-md-1 text-center">
	<%= form_tag artists_path, method: :get do %>
		<div class="form-group mb-3">
			<%= text_field_tag :search, nil, class: 'form-control', placeholder: 'Buscar artista' %>
		</div>

		<%= submit_tag 'Buscar', class: 'btn btn-primary mb-5' %>
	<% end %>

	<% unless @artists.blank? %>
		<div class="row">
			<% @artists.each do |artist| %>
				<div class="col-md-4 col-sm-6">
					<div class="card" style="height: 35rem; margin-bottom: 2em;">
						<%= image_tag artist.images&.last&.fetch('url') || 'https://via.placeholder.com/160x160', class: "card-img-top", alt: 'https://via.placeholder.com/160x160' %>
						<div class="card-body">
							<h5 class="card-title"><%= artist.name %></h5>
							<%= link_to 'Ver artista', "/artists/#{artist.id}", class: 'btn btn-info' %>
						</div>
					</div>	
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/artists/show.html.erb
<h3 class="text-center"><%= @artist.name %></h3>
<div class="text-center">
	<%= image_tag @artist.images.first.fetch('url') || 'https://via.placeholder.com/640x640', width: 300 %>
</div>

<hr>
<h4 class="text-center mb-5">Canciones más escuchadas</h4>

<div class="row" data-controller="tracks">
	<% @top_tracks.each do |track| %>
		<div class="col-md-4 col-sm-6">
			<div class="card" style="height: 35rem; margin-bottom: 2em;">
				<%= image_tag track.album.images.select{|i| i['height'] == 300 }.first['url'] || 'https://via.placeholder.com/300x300', class: "card-img-top", alt: 'https://via.placeholder.com/160x160' %>
				<div class="card-body text-center">
					<h5 class="card-title"><%= track.name %></h5>
					<p><b>Album: </b><%= track.album.name %></p>
					<% unless @track_ids.include?(track.id) %>
						<%= link_to 'Agregar a Playlist', nil, class: 'btn btn-success', data: { action: 'click->tracks#addToPlaylist', track_id: track.id } %>
					<% else %>
						<b>La cancion ya ha sido agregada al playlist. Se tocara proximamante!</b>
					<% end %>
				</div>
			</div>	
		</div>
	<% end %>
</div>

app/views/home/index.html.erb
<% if current_user.present? %>
	<div class="text-center">
		<div clas="row">
			<div class="col-md-6">
				<%= link_to 'Mis Canciones', current_user, method: :post, class: 'btn btn-success mb-3' %>
			</div>
			<div class="col-md-6">
				<%= link_to 'Proximas canciones a agregar', '#', method: :post, class: 'btn btn-info mb-3' %>
			</div>
		</div>
		
		<div clas="row">
			<div class="col-md-6">
				<%= link_to 'Mis Canciones', current_user, method: :post, class: 'btn btn-success mb-3' %>
			</div>
			<div class="col-md-6">
				<%= link_to 'Proximas canciones a agregar', '#', method: :post, class: 'btn btn-info mb-3' %>
			</div>
		</div>

		<% if current_user.admin? %>
			<hr>
			<h3>Administrador</h3>
			<p>
				<%= link_to 'Autenticar Aplicacion con Spotify', '/auth/spotify', method: :post, class: 'btn btn-success' %>
			</p>
		<% end %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocola</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
          <%= link_to root_path, class: 'navbar-brand' do %>
						Rocola
          <% end %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav justify-content-end">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Playlist', root_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Mis Canciones', current_user, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Buscar Canciones', tracks_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Buscar por Artista', artists_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= button_to 'Salir', destroy_user_session_path, class: 'nav-link', method: :delete, class: 'btn btn-link nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Ingresar', new_user_session_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Crear cuenta', new_user_registration_path, class: 'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if notice %>
      <div class="alert alert-dismissible alert-success">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-dismissible alert-danger">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <%= alert %>
      </div>
    <% end %>

    <div id="main" class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/playlists/index.html.erb
<div class="col-md-10 offset-md-1 text-center">
	<% if @playlists.any? %>
		<h4 class="mb-5">Mis playlists:</h4>

		<div class="row mb-5">
			<% @playlists.each do |playlist| %>
				<div class="col-md-4 col-sm-6">
					<div class="card" style="height: 30rem; margin-bottom: 1em;">
						<%= image_tag playlist.images.first['url'], class: "card-img-top", alt: 'https://via.placeholder.com/160x160' %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= playlist.name %></h5>
							<p><b>Descripcion: </b><%= playlist.description %></p>
							<%= link_to 'Ver playlist', playlist_path(playlist.id), class: 'btn btn-success' %>
						</div>
					</div>	
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/playlists/show.html.erb
<h4 class="text-center mb-5">Ultimas canciones agregadas al playlist:</h4>

<div class="row" data-controller="tracks">
	<% @playlist.tracks.reverse.each do |track| %>
		<div class="col-md-4 col-sm-6">
			<div class="card" style="height: 30rem; margin-bottom: 2em;">
				<%= image_tag track.album.images.select{|i| i['height'] == 300 }.first['url'] || 'https://via.placeholder.com/300x300', class: "card-img-top", alt: 'https://via.placeholder.com/160x160' %>
				<div class="card-body text-center">
					<h5 class="card-title"><%= track.name %></h5>
					<p><b>Album: </b><%= track.album.name %></p>
				</div>
			</div>	
		</div>
	<% end %>
</div>

app/views/tracks/index.html.erb
<h3 class="text-center">Buscar canción</h3>

<div class="text-center" data-controller="tracks">
	<%= form_tag tracks_path, method: :get do %>
		<div class="form-group mb-3">
			<%= text_field_tag :search, nil, class: 'form-control', placeholder: 'Buscar canción' %>
		</div>

		<%= submit_tag 'Buscar', class: 'btn btn-primary mb-5' %>
	<% end %>

	<% unless @tracks.nil? %>
		<div class="row">
			<% @tracks.each do |track| %>
				<div class="col-md-4 col-sm-12">
					<div class="card" style="height: 35rem; margin-bottom: 2rem;">
						<%= image_tag track.album.images.select{|i| i['height'] == 300 }.first['url'] || 'https://via.placeholder.com/300x300', class: "card-img-top", alt: 'https://via.placeholder.com/160x160' %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= track.name %></h5>
							<p><b>Artista: </b><%= track.artists.map(&:name).join(' & ') %></p>
							<% unless @track_ids.include?(track.id) %>
								<%= link_to 'Agregar a Playlist', nil, class: 'btn btn-success', data: { action: 'click->tracks#addToPlaylist', track_id: track.id } %>
							<% else %>
								<b>La cancion ya ha sido agregada al playlist. Se tocara proximamante!</b>
							<% end %>
						</div>
					</div>	
				</div>
			<% end %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-10 offset-md-1 text-center" data-controller="tracks">
	<% unless @tracks.nil? %>
		<h4 class="mb-5">Canciones que se agregaran al playlist:</h4>

		<div class="row mb-5">
			<% @tracks.each do |track| %>
				<div class="col-md-4 col-sm-12">
					<div class="card" style="height: 35rem; margin-bottom: 2rem;">
						<%= image_tag track.album_image_url, class: "card-img-top", alt: 'https://via.placeholder.com/160x160' %>
						<div class="card-body text-center">
							<h5 class="card-title"><%= track.name %></h5>
							<p><b>Artista: </b><%= track.artist %></p>
							<%= link_to 'Quitar de la lista', nil, class: 'btn btn-warning', data: { action: 'click->tracks#removeFromPlaylist', track_id: track.spotify_track_id } %>
						</div>
					</div>	
				</div>
			<% end %>
		</div>
	<% end %>

	<% if current_user.admin? %>
		<%= link_to 'Autenticar Aplicacion con Spotify', '/auth/spotify', method: :post, class: 'btn btn-success' %>
	<% end %>
</div>